security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
server:
  port: 8082
  servlet:
    context-path: /register

spring:
  application:
    name: registration-service
  main:
      allow-bean-definition-overriding: true
      

    
    